version: "3.8"
name: remember
services:
  web:
    build:
      context: .
      target: web
    volumes:
      - data:/data
    ports:
      - 3000:3000
    env_file:
      - "packages/web/.env.local"
    environment:
      REDIS_HOST: redis
      DATABASE_URL: "file:/data/db.db"
    depends_on:
      migration:
        condition: service_completed_successfully
  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  workers:
    build:
      context: .
      target: workers
    volumes:
      - data:/data
    env_file:
      - "packages/workers/.env"
    environment:
      REDIS_HOST: redis
      DATABASE_URL: "file:/data/db.db"
    depends_on:
      migration:
        condition: service_completed_successfully
  migration:
    build:
      context: .
      target: db
    environment:
      DATABASE_URL: "file:/data/db.db"
    volumes:
      - data:/data

volumes:
  redis:
  data:
