version: "3.8"
services:
  web:
    image: ghcr.io/mohamedbassem/hoarder-web:latest
    volumes:
      - data:/data
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATABASE_URL: "/data/db.db"
  redis:
    image: redis:7.2-alpine
    volumes:
      - redis:/data
  meilisearch:
    image: getmeili/meilisearch:v1.6
    volumes:
      - meilisearch:/meili_data
  workers:
    image: ghcr.io/mohamedbassem/hoarder-workers:latest
    volumes:
      - data:/data
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATABASE_URL: "/data/db.db"
      # OPENAI_API_KEY: ...
    depends_on:
      web:
        condition: service_started

volumes:
  redis:
  meilisearch:
  data:
