services:
  hoarder:
    build:
      dockerfile: docker/Dockerfile
      context: ../../
      target: aio
    restart: unless-stopped
    ports:
      - "${HOARDER_PORT:-3000}:3000"
    environment:
      DATA_DIR: /tmp
      NEXTAUTH_SECRET: secret
