name: Build and lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-lint:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # This is a workaround for: https://github.com/actions/setup-node/issues/899
      - name: Enable Corepack before setting up Node
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "pnpm"
      - name: Install deps
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
        run: pnpm install
      - name: Format
        run: pnpm format:check
      - name: Lint
        run: pnpm lint
      - name: Build the workers package
        working-directory: packages/workers
        run: pnpm typecheck
      - name: Build web app
        working-directory: packages/web
        run: pnpm run build
      - name: Build the browser extension
        working-directory: packages/browser-extension
        run: pnpm build
